### ISSUE TITLE
NTR: green manure exposure

### ISSUE THREAD

**Issue by richardostler** [Planteome/plant-experimental-conditions-ontology#116]
Can **green manure exposure** be added as a subclass of [natural fertilizer exposure](http://purl.obolibrary.org/obo/PECO_0007087)

**Comment by cooperl09** [comment]
Proposed name and def'n: 
[Term]
id: PECO:0001069
name: green manure exposure
def: "A natural fertilizer exposure (PECO:0007087) which is the application of green manure." []
comment: Green manure is created by leaving uprooted or sown crop parts to wither on a field so that they serve as a mulch and soil amendment. The plants used for green manure are often cover crops grown primarily for this purpose. {xref="Wikipedia:Green_manure"}

**Comment by richardostler** [comment]
Thanks I think this is fine.
