### ISSUE TITLE
NTR: liming exposure

### ISSUE THREAD

**Issue by richardostler** [Planteome/plant-experimental-conditions-ontology#119]
Please can you add a new term for liming exposure
**Name:** liming exposure
**definition:** A treatment involving the application of calcium or magnesium rich materials to reduce soil acidity. {xref="Wikipedia:Liming_(soil)"}
**subclass of:** [http://purl.obolibrary.org/obo/PECO_0007189](http://purl.obolibrary.org/obo/PECO_0007189), although it could sit under pH exposure?

I think this is different, or at least narrower than the pH exposure concept. I think pH exposure would be used to capture a controlled environment study where a treatment factor is the pH level, whereas liming is an agronomic process in which different rates of liming material e.g. ground chalk, are applied to the plots. Obviously this will achieve a pH gradient across plots, but it is the liming rate rather than subsequent the soil pH which is the treatment factor. Experiments will also often study the residual effects of the original exposure over several years and soil pH will naturally change.

thanks

**Comment by cooperl09** [comment]
Hi Richard, 
I have been looking at this term and trying to sort out where it would fit best.  From what I have read, lime generally consists of calcium carbonate and is applied to the soil, as a pretreatment to raise the soil pH.  So the plants are not actually being exposed to the CaCO3, but to a range of pH treatments.  Propose adding it as a child of salt exposure (PECO:0007185)  and part of the  basic pH soil environment exposure (PECO:0007062).

**Comment by cooperl09** [comment]
This term has been created and is available at https://browser.planteome.org/amigo/term/PECO:0001070

id: PECO:0001070
name: calcium carbonate exposure
def: "A salt exposure (PECO:0007185) which is a treatment with calcium carbonate (CHEBI:3311) in order to raise the pH of the growing media." [PECO:cooperl]
synonym: "lime exposure (broad)" BROAD []
is_a: PECO:0007185 ! salt exposure
relationship: part_of PECO:0007133 ! basic pH growth media environment exposure
created_by: cooperl
creation_date: 2019-09-20T22:36:52Z
